version: '3.3'

services:
    nginx:
        image: nginx:latest
        ports:
            - "80:80"
            # Port for xdebug (ensure this matches the remote_port in the xdebug.ini)
            - "9001:9001"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/config/site.conf:/etc/nginx/conf.d/default.conf
        links:
            - php
        networks:
            - pimcorenet

    php:
        build: ./docker/php
        volumes:
            - .:/var/www/html
            - ./docker/php/config/custom.ini:/usr/local/etc/php/conf.d/custom.ini
        networks:
            - pimcorenet
networks:
    pimcorenet:
