_pimcore:
    resource: "@PimcoreCoreBundle/Resources/config/routing.yml"

my_custom_admin_entry_point:
    path: /admin-cp
    controller: Pimcore\Bundle\CoreBundle\Controller\PublicServicesController::customAdminEntryPointAction